import os
import sys
import json
import logging
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

logger = logging.getLogger("GitHubUploader")


class GitHubUploader:
    def __init__(self, config_obj=None):
        self.config = config_obj

    def _get_headers(self, token: str) -> dict:
        return {
            "Authorization": f"Bearer {token.strip()}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "Local-Developer-CRM"
        }

    def test_connection(self) -> dict:
        """Verify repository access and token validity."""
        from backend.config import config
        token = config.github_token
        owner = config.github_username
        repo = config.github_repo

        if not token or not owner or not repo:
            return {
                "success": False,
                "error": "GitHub credentials missing in .env. Please specify GITHUB_USERNAME, GITHUB_REPO, and GITHUB_TOKEN."
            }

        url = f"https://api.github.com/repos/{owner}/{repo}"
        req = urllib.request.Request(url, headers=self._get_headers(token))

        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                return {
                    "success": True,
                    "message": f"Successfully connected to GitHub repository '{data.get('full_name')}'.",
                    "repo_url": data.get("html_url")
                }
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return {"success": False, "error": f"Repository '{owner}/{repo}' not found or token lacks access."}
            elif e.code == 401:
                return {"success": False, "error": "GitHub token authentication failed (Unauthorized)."}
            return {"success": False, "error": f"GitHub API error: {e.code} {e.reason}"}
        except Exception as e:
            return {"success": False, "error": f"Connection error: {str(e)}"}

    def _get_or_create_release(self, owner: str, repo: str, token: str, tag: str, title: str) -> dict:
        """Fetch existing release by tag or create a new one."""
        headers = self._get_headers(token)
        get_url = f"https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}"
        
        # Try fetching existing release
        try:
            req = urllib.request.Request(get_url, headers=headers)
            with urllib.request.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            if e.code != 404:
                raise e

        # Create new release if not found
        create_url = f"https://api.github.com/repos/{owner}/{repo}/releases"
        payload = json.dumps({
            "tag_name": tag,
            "name": title,
            "body": f"Automated APK Release build generated by Local Developer CRM on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "draft": False,
            "prerelease": False
        }).encode("utf-8")

        req = urllib.request.Request(create_url, data=payload, headers={**headers, "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            if e.code == 422:
                # Handle empty repository case by creating initial README.md commit
                self._ensure_repo_initialized(owner, repo, token)
                req_retry = urllib.request.Request(create_url, data=payload, headers={**headers, "Content-Type": "application/json"})
                with urllib.request.urlopen(req_retry, timeout=15) as resp_retry:
                    return json.loads(resp_retry.read().decode("utf-8"))
            raise e

    def _ensure_repo_initialized(self, owner: str, repo: str, token: str):
        """Create README.md via Contents API if repository is empty."""
        import base64
        headers = self._get_headers(token)
        url = f"https://api.github.com/repos/{owner}/{repo}/contents/README.md"
        content_b64 = base64.b64encode(b"# App Releases Repository\nAutomated APK Releases.").decode("utf-8")
        payload = json.dumps({
            "message": "Initial commit for release repository",
            "content": content_b64
        }).encode("utf-8")
        req = urllib.request.Request(url, data=payload, headers={**headers, "Content-Type": "application/json"}, method="PUT")
        try:
            with urllib.request.urlopen(req, timeout=15):
                pass
        except Exception as e:
            logger.warning(f"Repo auto-init result: {e}")

    def _delete_existing_asset(self, owner: str, repo: str, token: str, release: dict, filename: str):
        """Delete old asset with matching filename from release to allow overwrite."""
        headers = self._get_headers(token)
        assets = release.get("assets", [])
        for asset in assets:
            if asset.get("name") == filename:
                asset_id = asset.get("id")
                del_url = f"https://api.github.com/repos/{owner}/{repo}/releases/assets/{asset_id}"
                req = urllib.request.Request(del_url, headers=headers, method="DELETE")
                try:
                    with urllib.request.urlopen(req, timeout=15):
                        pass
                except Exception as e:
                    logger.warning(f"Could not delete old asset {asset_id}: {e}")

    def upload_apk(self, file_path: str, metadata: dict) -> dict:
        """
        Upload APK to GitHub Releases via REST API.
        """
        from backend.config import config
        path = Path(file_path)
        if not path.exists():
            return {"success": False, "error": f"File not found: {file_path}"}

        token = config.github_token
        owner = config.github_username
        repo = config.github_repo
        tag = metadata.get("github_release_tag") or config.get_project_release_tag()
        filename = path.name

        if not token or not owner or not repo:
            return {"success": False, "error": "GitHub credentials missing in .env file."}

        try:
            # 1. Get or create release for project tag
            proj_name = metadata.get("project_name") or config.project_name
            release_title = f"{proj_name} - Latest Release (v{metadata.get('version', '1.0.0')})"
            release = self._get_or_create_release(owner, repo, token, tag, release_title)

            # 2. Delete previous asset if present
            self._delete_existing_asset(owner, repo, token, release, filename)

            # 3. Upload new asset binary
            upload_url = release.get("upload_url", "").split("{")[0]
            target_upload_url = f"{upload_url}?name={filename}"

            with open(path, "rb") as f:
                file_bytes = f.read()

            upload_headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/vnd.android.package-archive",
                "Content-Length": str(len(file_bytes)),
                "User-Agent": "Local-Developer-CRM"
            }

            req = urllib.request.Request(target_upload_url, data=file_bytes, headers=upload_headers)
            with urllib.request.urlopen(req, timeout=120) as resp:
                asset_data = json.loads(resp.read().decode("utf-8"))

            download_url = asset_data.get("browser_download_url") or f"https://github.com/{owner}/{repo}/releases/download/{tag}/{filename}"
            now_formatted = datetime.now().strftime("%d %b %Y, %I:%M %p")

            # 4. Optionally also tag a versioned release for historical permanent archiving
            version_str = metadata.get("version", "1.0.0")
            build_str = metadata.get("build_number", "")
            ver_tag = f"v{version_str}-build{build_str}" if build_str else f"v{version_str}"
            
            try:
                ver_release = self._get_or_create_release(owner, repo, token, ver_tag, f"Release {ver_tag}")
                self._delete_existing_asset(owner, repo, token, ver_release, filename)
                req_ver = urllib.request.Request(f"{ver_release.get('upload_url', '').split('{')[0]}?name={filename}", data=file_bytes, headers=upload_headers)
                with urllib.request.urlopen(req_ver, timeout=120):
                    pass
            except Exception as e:
                logger.info(f"Versioned archive tag {ver_tag} skipped or logged: {e}")

            return {
                "success": True,
                "provider": "github",
                "download_url": download_url,
                "version": metadata.get("version"),
                "uploaded_at": datetime.now().isoformat(),
                "uploaded_at_formatted": now_formatted
            }

        except urllib.error.HTTPError as e:
            error_msg = f"GitHub API Error {e.code}: {e.reason}"
            try:
                body = json.loads(e.read().decode("utf-8"))
                if "message" in body:
                    error_msg += f" - {body['message']}"
            except Exception:
                pass
            return {"success": False, "error": error_msg}
        except Exception as e:
            return {"success": False, "error": f"Upload failed: {str(e)}"}


github_uploader = GitHubUploader()
